name: 'ibm'
attributes:
    beta: 0.999
    step: 2000     # Used in FlexileBender model. Constraint the changes of critical scenarios from iteration to iteration.
traffic_matrix:
    num_matrices: 1
    tm_index: 0
data: 
    cap_file: '../_data/ibm/ibm_capa.tab'
    tm_file: '../_data/ibm/ibm_traffic.tab'
    tunnel_file: '../_data/ibm/ibm_tunnel.tab'
    scenario_file: '../_data/ibm/ibm_scenario.tab'
